import { type Metadata } from 'next';
import { fetchQuery } from 'convex/nextjs';
import { api } from '../../../../convex/_generated/api';
import { Id } from '../../../../convex/_generated/dataModel';

export async function generateMetadata({
  params,
}: {
  params: { id: string };
}): Promise<Metadata> {
  let poem: Awaited<ReturnType<typeof fetchQuery<typeof api.poems.getById>>> | null = null;
  try {
    poem = await fetchQuery(api.poems.getById, { id: params.id as Id<'poems'> });
  } catch {
    // fall through to generic title
  }

  if (!poem || !poem.title) {
    return {
      title: 'Poem — Infinite Poetry',
      openGraph: { title: 'Poem — Infinite Poetry' },
      twitter: { title: 'Poem — Infinite Poetry' },
    };
  }

  const previewText = poem.lines.slice(0, 2).filter(Boolean).join(' / ');
  const description = previewText
    ? `${previewText}`
    : `A ${poem.styleName} generated by AI.`;

  return {
    title: `${poem.title} — Infinite Poetry`,
    description,
    openGraph: {
      type: 'article',
      title: poem.title,
      description,
      siteName: 'Infinite Poetry',
    },
    twitter: {
      card: 'summary_large_image',
      title: poem.title,
      description,
    },
  };
}

export default function PoemLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
