const FAQ = [
  {
    question: 'What is Infinite Poetry?',
    answer:
      'Infinite Poetry is a research project exploring what AI can and cannot do with constrained verse forms. Give it a topic and a poetic form — a Shakespearean sonnet, a villanelle, a sestina, a haiku, and more — and it generates a poem in that tradition using Claude Opus, Anthropic\'s most capable model. Optionally, it will pair the poem with an illustration generated by Google\'s Gemini image model, rendered in a historical art style of your choice.',
  },
  {
    question: 'Why AI poetry?',
    answer:
      'Let me be crystal clear from the outset. I do not want this tool to replace flesh-and-blood poets, nor do I think it ever could. Have you seen some of the poems this thing dreams up? Instead, I want to use this as a learning lab to discover more about poetry and about AI itself. Can AI teach us anything about existing verse forms? The very AI quirks that aggravate the mainstream may very well show us something new and interesting about poetry. On the flip side, poetry requires an immense level of creativity, lateral thinking, and diction. AI can only achieve simulacra of those things — but can we learn something by watching it try?',
  },
  {
    question: 'Why only five poems per day?',
    answer:
      'Those of you using the free tier of LLMs may be surprised to learn that running them costs real money. Someone, even if it\'s not you, pays for these computations. In this case, that someone is me — and since this is a self-funded research project, not a product, the daily limit keeps costs manageable. Image generation in particular is significantly more expensive than the poem itself, which is why you\'ll see a reminder to use it sparingly.',
  },
  {
    question: 'My poem\'s got gibberish in it!',
    answer:
      'I run the model at a high temperature, which controls how "creative" or "experimental" it\'s allowed to be. I err on the side of giving it more leeway, which means occasional lapses. Have a good laugh and try another one.',
  },
  {
    question: 'I want to get involved!',
    answer:
      'I would love that. For ideas, criticism, and kudos, find me on LinkedIn. I especially love hearing from other literary types. For developers, feel free to clone the GitHub repository and contribute.',
  },
  {
    question: 'About the Author',
    answer:
      'Hi, I\'m Seth Wilson! I\'m a legally blind software developer living in Tyler, Texas. I\'ve been working in tech for about seven years. Before that I lived in the world of academia, earning an MSt in Medieval History from Oxford University in 2006 and an MA in English from UT Tyler in 2016. I live at the intersection of the arts and sciences: jack of all trades, master of none.',
  },
];

export default function AboutPage() {
  return (
    <div className='max-w-3xl mx-auto px-4 py-12'>
      <header className='mb-10'>
        <h1
          className='text-4xl sm:text-5xl font-bold text-[var(--text-primary)] mb-3'
          style={{ fontFamily: 'var(--font-display), serif' }}
        >
          About
        </h1>
        <p className='text-[var(--text-secondary)] leading-relaxed'>
          Everything you wanted to know about Infinite Poetry—but were afraid to ask.
        </p>
      </header>

      <hr className='garden-divider' />

      <div>
        {FAQ.map(({ question, answer }) => (
          <details key={question} className='faq-item'>
            <summary>
              {question}
              <svg
                className='faq-chevron w-5 h-5'
                xmlns='http://www.w3.org/2000/svg'
                viewBox='0 0 24 24'
                fill='none'
                stroke='currentColor'
                strokeWidth={2}
                strokeLinecap='round'
                strokeLinejoin='round'
                aria-hidden='true'
              >
                <path d='m6 9 6 6 6-6' />
              </svg>
            </summary>
            <div className='faq-content'>{answer}</div>
          </details>
        ))}
      </div>
    </div>
  );
}
