/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yODSgiirP3b
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts

import { Button } from "@/components/ui/button"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"

export function Poetry() {
  return (
    <div className="px-4 py-6 md:px-6 md:py-12 lg:py-16 bg-white dark:bg-gray-950">
      <article className="prose prose-gray max-w-3xl mx-auto dark:prose-invert">
        <div className="flex items-center">
          <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl">Daffodils</h1>
          <Popover className="ml-2">
            <PopoverTrigger asChild>
              <Button className="rounded-full" size="icon" variant="ghost">
                <InfoIcon className="w-4 h-4" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-80">
              <div className="grid gap-4">
                <div className="space-y-2">
                  <h4 className="font-medium leading-none">Poetic Style and Explanation</h4>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    This poem, "Daffodils," is a classic example of Romantic poetry written by the renowned English poet
                    William Wordsworth. It showcases Wordsworth's ability to find beauty and wonder in the natural
                    world, using vivid imagery and personification to transport the reader into the scene.
                  </p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    The poem's structure follows a consistent rhyme scheme, with a rhythmic cadence that mimics the
                    swaying motion of the daffodils in the breeze. Wordsworth's use of descriptive language, such as
                    "fluttering and dancing" and "tossing their heads in sprightly dance," brings the daffodils to life
                    and invites the reader to share in the poet's sense of joy and awe.
                  </p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    The poem's central theme explores the power of nature to inspire and uplift the human spirit, even
                    in moments of solitude and contemplation. Wordsworth's ability to find solace and tranquility in the
                    natural world is a hallmark of Romantic poetry, and "Daffodils" stands as a timeless testament to
                    this enduring theme.
                  </p>
                </div>
              </div>
            </PopoverContent>
          </Popover>
        </div>
        <div className="space-y-4">
          <p>I wandered lonely as a cloud</p>
          <p>That floats on high o'er vales and hills,</p>
          <p>When all at once I saw a crowd,</p>
          <p>A host, of golden daffodils;</p>
          <p>Beside the lake, beneath the trees,</p>
          <p>Fluttering and dancing in the breeze.</p>
          <p>Continuous as the stars that shine</p>
          <p>And twinkle on the milky way,</p>
          <p>They stretched in never-ending line</p>
          <p>Along the margin of a bay:</p>
          <p>Ten thousand saw I at a glance,</p>
          <p>Tossing their heads in sprightly dance.</p>
        </div>
      </article>
    </div>
  )
}

function InfoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  )
}
**/
